M48
; DRILL file {KiCad 7.0.1} date Thu Feb 29 06:25:06 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-29T06:25:06-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X5.28Y14.155
X5.28Y8.375
T2
X20.0Y85.0
X75.0Y2.0
X130.0Y85.0
T3
X145.355Y34.361
T0
M30
